bpg:
  config:
    quantizer:   28                      # 0-51
    chroma:      420                     # 420, 422, 444
    color_space: 'ycbcr'                 # ycbcr, rgb, ycgco
    bit_depth:   10                      # 8-12
    lossless:    false